---

- name: configure linux settings
  become: true
  lineinfile:
    path: /etc/sysctl.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items: "{{ sysctl_settings }}"
    

- name: reload sysctl.conf settings
  become: true
  command: sysctl -p