---

- name: install other packages
  become: true
  apt:
    name:
      - git
      - silversearcher-ag
      - jq
      - mc
    state: present

- name: install HTTPie
  become: true
  pip:
    name:
      - httpie
      - mycli
    state: present

- name: install diff-so-fancy
  become: true
  get_url:
    url: https://raw.githubusercontent.com/so-fancy/diff-so-fancy/master/third_party/build_fatpack/diff-so-fancy
    dest: /usr/local/bin/diff-so-fancy

- name: Changing perm of diff-so-fancy
  become: true
  file:
    dest: /usr/local/bin/diff-so-fancy
    mode: a+x

- name: git config diff-so-fancy
  command: "{{ item }}"
  with_items:
    - "git config --global core.pager 'diff-so-fancy | less --tabs=4 -RFX'"
    - "git config --global color.ui true"
    - "git config --global color.diff-highlight.oldNormal    'red bold'"
    - "git config --global color.diff-highlight.oldHighlight 'red bold 52'"
    - "git config --global color.diff-highlight.newNormal    'green bold'"
    - "git config --global color.diff-highlight.newHighlight 'green bold 22'"
    - "git config --global color.diff.meta       'yellow'"
    - "git config --global color.diff.frag       'magenta bold'"
    - "git config --global color.diff.commit     'yellow bold'"
    - "git config --global color.diff.old        'red bold'"
    - "git config --global color.diff.new        'green bold'"
    - "git config --global color.diff.whitespace 'red reverse'"

