---

- name: add neovim ppa
  become: true
  apt_repository:
    repo: 'ppa:neovim-ppa/stable'

- name: install neovim
  become: true
  apt:
    name: neovim
    state: present
  register: install_nvim

- name: update alternative
  become: true
  command: "update-alternatives --install /usr/bin/vim vim /usr/bin/nvim 60"
  when: install_nvim.changed

- name: update alternative
  become: true
  command: "update-alternatives --config vim"
  when: install_nvim.changed

- name: install python 3 packages
  become: true
  apt:
    name:
      - python-dev
      - python-pip
      - python3-dev 
      - python3-pip
    state: present

- name: install neovim pip3
  become: true
  pip:
    executable: pip3
    name: neovim
    state: present

- name: make sure .config/vim exists
  file:
    path: ~/.config/nvim
    state: directory

- name: install Vim Plug
  stat:
    path: ~/.local/share/nvim/site/autoload/plug.vim
  register: plug_vim

- name: make sure /.local/share/nvim/site/autoload exists
  file:
    path: ~/.local/share/nvim/site/autoload
    state: directory
  when: plug_vim.stat.exists == false

- name: save Vim Plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.local/share/nvim/site/autoload/plug.vim
  when: plug_vim.stat.exists == false

- name: vimrc file
  copy:
    src: files/vimrc
    dest: ~/.config/nvim/init.vim